=== Crapoo/Blitz/BlitzEJB/ejbModule/blitz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="blitz">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="die" />
				<xs:element ref="card" minOccurs="1" maxOccurs="24"/>
			</xs:sequence>
			<xs:attribute name="goal" type="xs:string" />
			<xs:attribute name="nbCardsByPlayer" type="xs:int"
				use="required" />
			<xs:attribute name="nbTotalCards" type="xs:int" use="required" />
			<xs:attribute name="minPlayers" type="xs:int" use="required" />
			<xs:attribute name="maxPlayers" type="xs:int" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="die">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="face" maxOccurs="6" />
			</xs:sequence>
			<xs:attribute name="nbByPlayer" type="xs:int" use="required" />
			<xs:attribute name="nbTotalDice" type="xs:int" use="required" />

		</xs:complexType>
	</xs:element>

	<xs:element name="card">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="figure" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="ref" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="cost" type="xs:int" use="required" />
			<xs:attribute name="nb" type="xs:int" use="required" />
			<xs:attribute name="effect" type="xs:string" use="required" />
			<xs:attribute name="effectCode" type="xs:int" use="required" />
			<xs:attribute name="src" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="face">
		<xs:complexType>
			<xs:attribute name="figure" type="xs:string" use="required" />
			<xs:attribute name="identif" type="xs:string" use="required" />
			<xs:attribute name="src" type="xs:string" />
			<xs:attribute name="nbFaces" use="required" type="dieType" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="dieType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="6" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Crapoo/Blitz/BlitzEJB/ejbModule/blitz.xml
<?xml version="1.0" encoding="UTF-8"?>
<blitz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="blitz.xsd"
	goal=" être le premier joueur à ne plus avoir de dé. ">
	<dice nbByPlayer="4" totalNbDices="24">
		<face figure="blitz" identif="b" src="images/" nbFaces="3"></face>
		<face figure="dice" identif="d" nbFaces="1"></face>
		<face figure="card" identif="c" nbFaces="2"></face>
	</dice>
	<!-- TODO vérifier pour le nombre de carte - ajouté dans ce XML pour le moment  -->
	<cards nbCardsByPlayer="3" totalNbCards="36" minPlayers="2"
		maxPlayers="6">
		<card cost="1" nb="5" effect="Supprimez 1 de vos dés" src="images/"
			effectCode="1">
			Le dé est retiré de la partie.On ne peut pas jouer cette carte si on
			obtient dans le même tour 2 figures
			<figure ref="d" />
			ou plus avec ses dés.
		</card>
		<card cost="2" nb="5" effect="Changez de sens" src="images/" effectCode="2">
			Tous les joueurs donnent leurs dés à leur
			voisin de gauche ou de
			droite selon le choix du joueur qui pose la
			carte. (Il doit lui aussi
			donner ses dés).
		</card>
		<card cost="3" nb="4" effect="Supprimez 2 de vos dés" src="images/"
			effectCode="3">Les dés sont retirés de la
			partie.
		</card>
		<card cost="3" nb="4" effect="Donnez 1 de vos dés au joueur de votre choix"
			src="images/" effectCode="4">
			L’effet est indépendant des dés que vous avez peut-être déjà donnés
			avec la ou les figure(s)
			<figure ref="d" />
			.
		</card>
		<card cost="1" nb="3" effect="Prenez 1 carte au joueur de votre choix"
			src="images/" effectCode="5">Le joueur vous présente ses cartes en
			éventail faces cachées, prenez celle de votre choix. Si
			aucun joueur
			n’a de carte prenez-en une dans la pioche.
		</card>
		<card cost="1" nb="3" effect="Le joueur de votre choix n’a plus qu’1 carte"
			src="images/" effectCode="6">Le joueur choisi doit avoir au moins 2
			cartes
			en main. Il choisit alors la carte qu’il souhaite conserver et
			se
			défausse des autres.
		</card>

		<card cost="1" nb="3" effect="Piochez 3 cartes dans la pioche" src="images/"
			effectCode="7">
			L’effet est indépendant des cartes que vous avez peut-être obtenues
			avec la ou les figure(s)
			<figure ref="c" />
			.
		</card>

		<card cost="2" nb="3" effect="Tous les joueurs sauf vous n’ont plus que 2 cartes"
			src="images/" effectCode="8">Les joueurs ayant plus de 2 cartes
			choisissent celles qu’ils souhaitent conserver et se défaussent des
			autres.
		</card>

		<card cost="0" nb="3" effect="Le joueur de votre choix passe son tour"
			src="images/" effectCode="9">Posez la carte, face visible, devant le
			joueur choisi qui la conserve jusqu’à ce qu’il ait passé son tour
			puis la défausse. Plusieurs de ces cartes peuvent se cumuler devant
			le
			même joueur.
		</card>
		<card cost="0" nb="3" effect="Rejouez et changement de sens" src="images/"
			effectCode="10">Le joueur rejoue et la partie continue
			dans le sens inverse.
		</card>

	</cards>
</blitz>
